version: '3'

services:
    # Run a framd instance listening for ED connection
    fram:
      image: fram
      container_name: fram
      ports:
        - "8187:8087"
      environment:
        - LICENSE
        - PASS

    # Run a tomcat which will connect to the above fram
    tomcat:
      image: edtomcat
      depends_on:
        - fram
      ports:
        - 8080
        - 8088
      environment:
        - TARGET=fram
        - GROUPS=production,tomcat
        - LICENSE
        - PASS=
